Add missing argument in depthCache method
Add missing argument to avoid the following error: "Too few arguments to function Binance\API::depth()" when using depth cache via WebSockets